export const data = {
  msg: "Datos recibidos",
  data: [
    {
      id: 1,
      nombre: "Kyle Simpson",
      email: "simpson@mail.com",
      edad: "35",
      password: "123%$·",
      telefono: "123432345",
      sexo: "masculino",
    },
    {
      id: 2,
      nombre: "Kyra Simpson",
      email: "ksimpson@mail.com",
      edad: "25",
      password: "1236548jn",
      telefono: "800432345",
      sexo: "femenino",
    },
    {
      id: 3,
      nombre: "Homero Simpson",
      email: "hsimpson@mail.com",
      edad: "55",
      password: "donuts",
      telefono: "555333444",
      sexo: "masculino",
    },
    {
      id: 4,
      nombre: "Lisa Sánchez",
      email: "sanchez@mail.com",
      edad: "24",
      password: "asd4561",
      telefono: "800555241",
      sexo: "femenino",
    },
    {
      id: 5,
      nombre: "María Mercedes",
      email: "mercedes@mail.com",
      edad: "45",
      password: "ñlkñ_:-12",
      telefono: "300026588",
      sexo: "femenino",
    },
    {
      id: 6,
      nombre: "Laura Espinoza",
      email: "espinoza@mail.com",
      edad: "55",
      password: "lkjiop8987",
      telefono: "663552441",
      sexo: "femenino",
    },
    {
      id: 7,
      nombre: "Bill Pay",
      email: "pay@mail.com",
      edad: "65",
      password: "payforeverything",
      telefono: "987456123",
      sexo: "masculino",
    },
    {
      id: 8,
      nombre: "Pedro Gates",
      email: "gates@mail.com",
      edad: "35",
      password: "12345678",
      telefono: "555444222",
      sexo: "masculino",
    },
    {
      id: 9,
      nombre: "Carlos Pascal",
      email: "pascal@mail.com",
      edad: "20",
      password: "999888777",
      telefono: "987456112",
      sexo: "masculino",
    },
    {
      id: 10,
      nombre: "Lupita Ferrer",
      email: "ferrer@mail.com",
      edad: "70",
      password: "asdinhyYHBGjjh",
      telefono: "333159756·",
      sexo: "masculino",
    },
  ]
}